version: "3.8"

services:
  game-shop:
    container_name: game-shop
    image: game-shop:latest
    ports:
      - 8000:8000
    environment:
      PORT: :8000
      MONGODB_URI: mongodb://root:root@mongodb:27017/game-shop
      SECRET: secret
      GIN_MODE: release
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: game-shop
    volumes:
      - mongo-data:/data/db
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mongo-data:
    driver: local
